spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
#      routes:
#        - id: feed-service
#          uri: http://localhost:8090
#          predicates:
#            - Path=/posts/**

  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:

            issuer-uri: http://localhost:8181/realms/inclusify-ms-realm
        registration:
          keycloak-spring-gateway-client:
            scope: openid
            provider: my-keycloak-provider
            client-id: ms-auth
            client-secret: prloMH0NZEbr8aNYR3UZBfUCrsT2T56p
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:9999/login/oauth2/code/keycloak'
