version: '3.9'

## NOTE: use the script 'start-docker-compose' to run this

services:

  mariadb-server:
    image: mariadb:10.6.13
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 'abcXYZ123$'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mariadb-server-vol:/var/lib/mysql
    networks:
      - demo-network

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    depends_on:
      - mariadb-server
    environment:
      PMA_HOST: mariadb-server
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8180:80
    networks:
      - demo-network

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - phpMyAdmin
    command: mariadb-server:3306
    networks:
      - demo-network


  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    ports:
      - 8181:8080
    command: -v start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_FEATURE: token-exchange,admin-fine-grained-authz
      KC_DB: mariadb
      KC_DB_URL_HOST: mariadb-server
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 3306
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: xyz123ABC$
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      - demo-network

networks:
  demo-network:

volumes:
  mariadb-server-vol:




#services:
#  keycloak:
#    image: quay.io/keycloak/keycloak:21.1.1
#    command: start-dev # -v start-dev --import-realm
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_DB: postgres
#      KC_DB_URL_HOST: postgres_keycloak
#      KC_DB_SCHEMA: public
#      KC_DB_URL_DATABASE: keycloak
#      KC_DB_USERNAME: keycloak
#      KC_DB_PASSWORD: kcpasswd
#      KC_DB_URL_PORT: 5432
#    ports:
#      - "8890:8080"
#    depends_on:
#      postgres_keycloak:
#        condition: service_healthy
#    networks:
#      - local
#
#
#  postgres_keycloak:
#    image: "postgres:14.2"
#    command: postgres -c 'max_connections=200'
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#      #- ./sql:/docker-entrypoint-initdb.d/:ro # turn it on, if you need run init DB
#    environment:
#      POSTGRES_DB: keycloak
#      POSTGRES_USER: keycloak
#      POSTGRES_PASSWORD: kcpasswd
#    networks:
#      - local
#    healthcheck:
#      test: "exit 0"
#    ports:
#      - "5432:5432"
#
#networks:
#  local:
#    name: local
#    driver: bridge
#
#volumes:
#  postgres_data:
#
#
##services:
##  keycloak_server:
##    image: quay.io/keycloak/keycloak:22.0.4
##    command: start-dev
##    environment:
##      KC_BD: mysql
##      KC_DB_URL_HOST: mysql_keycloak
##      KC_DB_URL_DATABASE: keyclaok
##      KC_DB_PASSWORD: root
##      KC_DB_USERNAME: root
##      KC_DB_SCHEMA: public
##      KEYCLOAK_ADMIN: admin
##      KEYCLOAK_ADMIN_PASSWORD: admin
##    ports:
##      - "8890:8080"
##    depends_on:
##      mysql_keycloak:
##        condition: service_healthy
##    networks:
##      - keycloak_dev_network
##
##    mysql_keycloak:
##      image: mysql:12.2
##
